#!/bin/bash


if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
BRANCH=`git rev-parse --abbrev-ref HEAD`

if [[ "$BRANCH" == "master" || "$BRANCH" == release* ]]; then
	echo "You are on branch $BRANCH. Are you sure you want to commit to this branch?"
	echo "If so, commit with -n to bypass this pre-commit hook."
	exit 1
fi

# Would be better to do this maybe: https://gist.github.com/carlos-jenkins/89da9dcf9e0d528ac978311938aade43
.git/hooks/prevent-focused-tests.sh
# .git/hooks/trim-whitespace.sh

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
